### ISSUE TITLE
Navarathri Dussehra Dress Up

### ISSUE THREAD

**Issue by ajazgames** [GameDistribution/GD-AS3#1]
Navarathri Dussehra Dress Up
Navarathri Dussehra Dress up game is the new dress up game from ajazgames. 
The Navarathri festival is the Indina festival of nine nights celebrated every year. people celebrates the worshiping of nine forms of Goddess Shakti / Devi during these nine days. All Girls wants to look gorgeous during this occasion. 

http://www.ajazgames.com/dress-up/navarathri-dussehra-dress-up/Play/

**Comment by AleBles** [comment]
That's a nice game, but this platform isn't meant for advertising, please stick to reporting issues :)
